name: Build and Test
on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '[0-9].*'

jobs:
  build-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          cd ${{ github.workspace }}/..
          rm -rf ${{ github.workspace }}
          git clone git@github.com:${{ github.repository }} ${{ github.workspace }}
          cd ${{ github.workspace }}
          git checkout ${{ github.ref }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: /bin/sh ./gradlew test installShadowDist
      - uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: build/reports
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: build/install