name: Docker Build
on: [push]

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: /bin/sh ./gradlew test shadowJar
      - uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: build/reports
      - uses: actions/upload-artifact@v1
        with:
          name: jar
          path: build/libs

  build-docker:
    runs-on: ubuntu-latest
    needs: build-jar

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: jar
      - run: ls -l