name: Docker Build
on: [push]

jobs:
  build-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: /bin/sh ./gradlew test installShadowDist
      - uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: build/reports
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: build/install

  build-docker:
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '/master')
    needs: build-dist

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: dist
          path: docker/root
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: slugger/embysweeper
          username: ${{secrets.DKHUB_ID}}
          password: ${{secrets.DKHUB_KEY}}
          workdir: docker