name: Create Release
on:
  push:
#    tags:
#      - '[0-9].*'

jobs:
  create-dist-zip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: frabert/replace-string-action@v1.1
        id: str_replace
        with:
          pattern: '.+/(.+)'
          string: ${{ github.ref }}
          replace-with: '$1'
      - uses: cschleiden/replace-tokens@v1
        with:
          files: 'src/main/resources/version.properties'
        env:
          GIT_SHA: ${{ github.sha }}
          GIT_BRANCH: ${{ github.ref }}
          APP_VER: ${{ steps.str_replace.outputs.replaced }}
      - name: Build with Gradle
        run: /bin/sh ./gradlew test shadowDistZip
      - uses: actions/upload-artifact@v2-preview
        with:
          name: test-results
          path: build/reports
      - uses: actions/upload-artifact@v2-preview
        with:
          name: dist
          path: build/distributions/*.zip

  create-release:
    runs-on: ubuntu-latest
    needs: create-dist-zip

    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist
      - name: unzip asset
        run: |
          mkdir tmp
          cd tmp
          unzip ../*.zip
          echo "##[set-output name=distfile;]$(ls -1 *.zip)"
        working-directory: dist
        id: dist_file
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/tmp/${{ steps.dist_file.outputs.distfile }}
          asset_name: ${{ steps.dist_file.outputs.distfile }}
          asset_content_type: application/zip