name: Create Release
on:
  push:
    tags:
      - '[0-9].*'

jobs:
  create-dist-zip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: frabert/replace-string-action@v1.1
        id: str_replace
        with:
          pattern: '.+/(.+)'
          string: ${{ github.ref }}
          replace-with: '$1'
      - uses: cschleiden/replace-tokens@v1
        with:
          files: 'src/main/resources/version.properties'
        env:
          GIT_SHA: ${{ github.sha }}
          GIT_BRANCH: ${{ github.ref }}
          APP_VER: ${{ steps.str_replace.outputs.replaced }} (${GITHUB_SHA::8})
      - name: Build with Gradle
        run: /bin/sh ./gradlew test installShadowDist
      - uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: build/reports
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: build/install

  create-release:
    runs-on: ubuntu-latest
    needs: create-dist-zip

    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist
      - run: zip -r embysweeper embysweeper-shadow
        working-directory: dist
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/embysweeper.zip
          asset_name: embysweeper.zip
          asset_content_type: application/zip